---
 - name: ansible
   hosts: all
   become: yes
   become_user: root

   tasks:
     - name: Install (git, apache2 unzip, curl)
       apt:
         pkg:
           - apache2
           - unzip
           - curl
           - git
           - wget
           - software-properties-common
         update_cache: yes

     # tasks file for php

     - name: php packages
       apt:
         pkg:
           - php8.1
           - libapache2-mod-php
           - php8.1-dev
           - php8.1-zip
           - php8.1-curl
           - php8.1-mbstring
           - php8.1-mysql
           - php8.1-gd
           - php8.1-xml
         update_cache: yes

     - name: ensure php8-fpm cgi.fix_pathinfo=0
       lineinfile: dest=/etc/php/8.1/apache2/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0

     - name: Update apt
       apt:
         update_cache: yes
         autoclean: yes

    # firewall stuff
     - name: Allow HTTP
       ufw:
         rule: allow
         port: "80"
         proto: tcp

     - name: Allow HTTPS
       ufw:
         rule: allow
         port: "433"
         proto: tcp

     - name: Allow SSH
       ufw:
         rule: allow
         port: "22"
         proto: tcp

     - name: Allow MySQL
       ufw:
         rule: allow
         port: "3306"
         proto: tcp

 # database
     - name: Update apt
       apt:
         update_cache: yes
         autoclean: yes
         autoremove: yes

     - name: Install Python3
       apt:
         name:  python3
         state: latest

     - name: Install Pip
       apt:
         name: pip
         state: latest


     - name: Install mysql server
       apt:
         name: mysql-server
         state: latest

     - name: Install mysql client
       apt:
         name: mysql-client
         state: latest

     - name: Install php-mysql
       apt:
         name: php-mysql
         state: latest

     - name: Install php sqlite
       apt:
         name: php-sqlite3
         state: latest


     - name: Install PyMySQL Library
       apt:
         name:  python3-mysqldb
         state: latest

     - name: Start the MySQL service
       service:
         name: mysql
         state: restarted
         enabled:

     - name: Install PyMySQL Library
       apt:
         name:  python3-mysqldb
         state: latest




     - name: Reload all Privileges
       command: sudo systemctl enable --now mysql

     - name: creating mysql user
       mysql_user:
        name: "laravel"
        password: "12345678"
        priv: '*.*:ALL'
        host: '%'
        state: present

     - name: creating datbase
       mysql_db:
        name: "laravel"
        state: present


     - name: Start the MySQL service
       service:
         name: mysql
         state: restarted
         enabled:


 # start work

     - name: Clone the project repo into a new directory
       git:
         repo: https://github.com/f1amy/laravel-realworld-example-app.git
         dest: /var/www/html/laravel-realworld-example-app
         clone: yes
         update: no



     - name: Copy file with owner and permissions
       ansible.builtin.copy:
        src: ~/ansible/postgres.sh
        dest: /var/www/html/laravel-realworld-example-app
        mode: '0777'



     - name: Create the web.php file in the routes directory
       copy:
         dest: /var/www/html/laravel-realworld-example-app/routes/web.php
         content: |
           <?php

           Route::get('/', function () {
               return view('welcome');
           });

     - name: Create an apache virtual host configuration file
       copy:
         dest: /var/www/html/laravel-realworld-example-app/.env
         content: |
           APP_NAME="Laravel Realworld Example App"
           APP_ENV=local
           APP_KEY=
           APP_DEBUG=true
           APP_URL= http://44.212.58.123
           APP_PORT=3000

           LOG_CHANNEL=stack
           LOG_DEPRECATIONS_CHANNEL=null
           LOG_LEVEL=debug

           DB_CONNECTION=mysql
           DB_HOST=127.0.0.1
           DB_PORT=3306
           DB_DATABASE=laravel
           DB_USERNAME=root
           DB_PASSWORD=12345678

           BROADCAST_DRIVER=log
           CACHE_DRIVER=file
           FILESYSTEM_DISK=local
           QUEUE_CONNECTION=sync
           SESSION_DRIVER=file
           SESSION_LIFETIME=120

           MEMCACHED_HOST=127.0.0.1

           REDIS_HOST=127.0.0.1
           REDIS_PASSWORD=null
           REDIS_PORT=6379

           MAIL_MAILER=smtp
           MAIL_HOST=mailhog
           MAIL_PORT=1025
           MAIL_USERNAME=null
           MAIL_PASSWORD=null
           MAIL_ENCRYPTION=null
           MAIL_FROM_ADDRESS="hello@example.com"
           MAIL_FROM_NAME="${APP_NAME}"

           AWS_ACCESS_KEY_ID=
           AWS_SECRET_ACCESS_KEY=
           AWS_DEFAULT_REGION=us-east-1
           AWS_BUCKET=
           AWS_USE_PATH_STYLE_ENDPOINT=false

           PUSHER_APP_ID=
           PUSHER_APP_KEY=
           PUSHER_APP_SECRET=
           PUSHER_APP_CLUSTER=mt1

           MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
           MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

           L5_SWAGGER_GENERATE_ALWAYS=true
           SAIL_XDEBUG_MODE=develop,debug
           SAIL_SKIP_CHECKS=true


     # Composer
     - name: Download php-composer
       get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/installer

     - name: install composer
       shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
       args:
        creates: /usr/local/bin/composer

     - name: rename composer.phar to composer
       shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
       args:
        creates: /usr/local/bin/composer

     - name: make composer executable
       file:
        path: /usr/local/bin/composer
        mode: a+x
        state: file


     # Remainder
     - name: Change file ownership, group and permissions
       file:
         path: /var/www/laravel-realworld-example-app
         state: directory
         recurse: yes
         owner: www-data
         group: www-data
         mode: '775'


     - name: Generate app key
       command:  "/usr/bin/php /var/www/html/laravel-realworld-example-app artisan key:generate"

     - name: Set up app storage link
       command: "/usr/bin/php /var/www/html/laravel-realworld-example-app artisan storage:link"

     - name: Run Migrations + Seeders
       command: "/usr/bin/php /var/www/html/laravel-realworld-example-app /artisan migrate --seed --force"


     - name: Create an apache virtual host configuration file
       copy:
         dest: /etc/apache2/sites-available/laravel.conf
         content: |
           <VirtualHost *:80>
               ServerAdmin 44.212.58.123
               ServerName
               ServerAlias 44.212.58.123
               DocumentRoot /var/www/html/laravel-realworld-example-app/public

               <Directory /var/www/html/laravel-realworld-example-app/public>
                   AllowOverride All
               </Directory>

               ErrorLog ${APACHE_LOG_DIR}/error.log
               CustomLog ${APACHE_LOG_DIR}/access.log combined
           </VirtualHost>


     - name: a2dissite 000-default.conf
       command: a2dissite 000-default.conf

     - name: Enable laravel page
       command: a2ensite laravel.conf


     - name: a2enmod rewrite
       command: a2enmod rewrite


     - name: restart apache
       service:
        state: restarted
        name: apache2
        daemon_reload: yes
